version: "3.1"
services:
  db:
    build:
      dockerfile: postgres.dockerfile
      context: ./
    image: resources-allocation-db
    container_name: resources-allocation-db-container
    restart: always
    environment:
      POSTGRES_PASSWORD: admin1234
      POSTGRES_USER: admin
      POSTGRES_DB: resources-allocation
    ports:
      - "5439:5432"
    networks:
      - resources-allocation-network

networks:
  resources-allocation-network:
    driver: bridge